let toggleBtn = document.getElementById("toggle");
let innerCircle = document.getElementById("innerCircle");
let priceTwo = document.getElementById("priceTwo");
let priceOneAnnual = document.getElementById("priceOneAnnual");
let priceTwoAnnual = document.getElementById("priceTwoAnnual");
let priceThreeAnnual = document.getElementById("priceThreeAnnual");
let annualy = document.getElementById("annualy");
let monthly = document.getElementById("monthly");
console.log(priceTwoAnnual);
toggleBtn.addEventListener("click", function() {
  innerCircle.classList.toggle("leftToggle");
  priceOne.classList.toggle("fade-out");
  priceTwo.classList.toggle("fade-out");
  priceThree.classList.toggle("fade-out");
  priceOneAnnual.classList.toggle("fade-in");
  priceTwoAnnual.classList.toggle("fade-in");
  priceThreeAnnual.classList.toggle("fade-in");
  monthly.classList.toggle("inactive");
  annualy.classList.toggle("active");
});
